langage: java

jdk: - oraclejdk8

notifications:
  email: on_success: never # default: change
  on_failure: always # default: always

  addons:
    sonarcloud:
      organization: "bahpetit"

  script:
    - mvn clean test -B
    - mvn cobertura: cobertura
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

  after_succes:
    - bash <(curl -s https://codecov.io/bash)